"use strict";

/* WeaverDeck v0.16.0 runtime extension for the stable plugin-core.js.
 * Applies a small, guarded textual patch in memory, then compiles the result.
 * The on-disk v0.15.0/v0.11.2-derived control core remains unchanged.
 */
const fs=require("fs");
const path=require("path");
const Module=require("module");
const filename=path.join(__dirname,"plugin-core.js");
let source=fs.readFileSync(filename,"utf8");
function replaceOnce(before,after,label){const first=source.indexOf(before);if(first<0)throw new Error(`v0.16.0 core patch failed: ${label} pattern not found`);if(source.indexOf(before,first+before.length)>=0)throw new Error(`v0.16.0 core patch failed: ${label} pattern is ambiguous`);source=source.slice(0,first)+after+source.slice(first+before.length)}
replaceOnce("  sourceMuteA:\"com.pipeweaver.opendeck.sourcemutea\", sourceMuteB:\"com.pipeweaver.opendeck.sourcemuteb\",\n  targetMixA:\"com.pipeweaver.opendeck.targetmixa\", targetMixB:\"com.pipeweaver.opendeck.targetmixb\", targetMixToggle:\"com.pipeweaver.opendeck.targetmixtoggle\",","  sourceMuteA:\"com.pipeweaver.opendeck.sourcemutea\", sourceMuteB:\"com.pipeweaver.opendeck.sourcemuteb\",\n  sourceLinkToggle:\"com.pipeweaver.opendeck.sourcelinktoggle\",\n  targetMixA:\"com.pipeweaver.opendeck.targetmixa\", targetMixB:\"com.pipeweaver.opendeck.targetmixb\", targetMixToggle:\"com.pipeweaver.opendeck.targetmixtoggle\",","action UUID");
replaceOnce("function sourceVolume(src,mix){const v=src?.volumes?.volume?.[mix];return Number.isFinite(v)?Number(v):null}\nfunction sourceMuted(src,mix){const st=src?.mute_states?.mute_state; if(Array.isArray(st)) return st.includes(\"Target\"+mix); if(typeof st===\"string\") return st.includes(\"Target\"+mix); return false}","function sourceVolume(src,mix){const v=src?.volumes?.volume?.[mix];return Number.isFinite(v)?Number(v):null}\nfunction sourceLinked(src){if(!src||!src.volumes||!(\"volumes_linked\" in src.volumes))return null;return src.volumes.volumes_linked!==null&&src.volumes.volumes_linked!==undefined}\nfunction sourceMuted(src,mix){const st=src?.mute_states?.mute_state; if(Array.isArray(st)) return st.includes(\"Target\"+mix); if(typeof st===\"string\") return st.includes(\"Target\"+mix); return false}","source link reader");
replaceOnce("  const sources=sourceDevices.map(d=>({name:deviceName(d),id:deviceId(d),volumeA:sourceVolume(d,\"A\"),volumeB:sourceVolume(d,\"B\"),mutedA:sourceMuted(d,\"A\"),mutedB:sourceMuted(d,\"B\")})).filter(x=>x.name&&x.id);","  const sources=sourceDevices.map(d=>({name:deviceName(d),id:deviceId(d),volumeA:sourceVolume(d,\"A\"),volumeB:sourceVolume(d,\"B\"),mutedA:sourceMuted(d,\"A\"),mutedB:sourceMuted(d,\"B\"),linked:sourceLinked(d)})).filter(x=>x.name&&x.id);","scene source snapshot");
replaceOnce("  const sourceActions=[ACTIONS.sourceVolUp,ACTIONS.sourceVolDown,ACTIONS.sourceSetVol,ACTIONS.sourceAVolUp,ACTIONS.sourceAVolDown,ACTIONS.sourceBVolUp,ACTIONS.sourceBVolDown,ACTIONS.sourceMute,ACTIONS.sourceMuteA,ACTIONS.sourceMuteB];\n  if(sourceActions.includes(a)){","  const sourceActions=[ACTIONS.sourceVolUp,ACTIONS.sourceVolDown,ACTIONS.sourceSetVol,ACTIONS.sourceAVolUp,ACTIONS.sourceAVolDown,ACTIONS.sourceBVolUp,ACTIONS.sourceBVolDown,ACTIONS.sourceMute,ACTIONS.sourceMuteA,ACTIONS.sourceMuteB];\n  if(a===ACTIONS.sourceLinkToggle){\n    const n=st.sourceName,d=findNamedSource(lastStatus,n),linked=sourceLinked(d);\n    setState(i.context,linked===true?1:0);\n    setTitle(i.context,`${n||\"Source\"}\\n${linked===null?\"?\":linked?\"LINKED\":\"UNLINKED\"}`);\n  } else if(sourceActions.includes(a)){","live key state");
replaceOnce("async function toggleSourceMute(i){const s=await refreshStatus(),n=i.settings.sourceName,mix=i.settings.mix||\"A\",src=findNamedSourceByName(s,n),id=src?.description?.id||src?.id;if(!src||!id){showAlert(i.context);return}const target=\"Target\"+mix,muted=sourceMuted(src,mix);const cmd=muted?{DelSourceMuteTarget:[id,target]}:{AddSourceMuteTarget:[id,target]};try{const r=await pipeCommand({Pipewire:cmd});if(!isOk(r))throw new Error(JSON.stringify(r));await refreshStatus();showOk(i.context)}catch(e){console.error(\"Source mute failed:\",e.message);showAlert(i.context)}}\nasync function setSourceVolume","async function toggleSourceMute(i){const s=await refreshStatus(),n=i.settings.sourceName,mix=i.settings.mix||\"A\",src=findNamedSourceByName(s,n),id=src?.description?.id||src?.id;if(!src||!id){showAlert(i.context);return}const target=\"Target\"+mix,muted=sourceMuted(src,mix);const cmd=muted?{DelSourceMuteTarget:[id,target]}:{AddSourceMuteTarget:[id,target]};try{const r=await pipeCommand({Pipewire:cmd});if(!isOk(r))throw new Error(JSON.stringify(r));await refreshStatus();showOk(i.context)}catch(e){console.error(\"Source mute failed:\",e.message);showAlert(i.context)}}\nasync function toggleSourceVolumeLink(i){const s=await refreshStatus(),n=i.settings.sourceName,src=findNamedSourceByName(s,n),id=deviceId(src),linked=sourceLinked(src);if(!src||!id||linked===null){showAlert(i.context);return}const next=!linked;try{const r=await pipeCommand({Pipewire:{SetSourceVolumeLinked:[id,next]}});if(!isOk(r)&&!JSON.stringify(r).includes(\"Requested State matches current state\"))throw new Error(JSON.stringify(r));await refreshStatus();showOk(i.context)}catch(e){console.error(\"Source volume link toggle failed:\",e.message);showAlert(i.context)}}\nasync function setSourceVolume","toggle implementation");
replaceOnce("    if([\"sourceMute\",\"sourceVolume\"].includes(type)){\n      if(!sources.length)add(errors,idx,type,\"No sources selected\");\n      for(const name of sources)if(!findNamedSource(status,name))add(errors,idx,type,`Source not found: ${name}`);\n      if(type===\"sourceVolume\"&&!vol())add(errors,idx,type,\"Volume must be a number from 0 to 100\");","    if([\"sourceMute\",\"sourceVolume\",\"sourceVolumeLink\"].includes(type)){\n      if(!sources.length)add(errors,idx,type,\"No sources selected\");\n      for(const name of sources)if(!findNamedSource(status,name))add(errors,idx,type,`Source not found: ${name}`);\n      if(type===\"sourceVolume\"&&!vol())add(errors,idx,type,\"Volume must be a number from 0 to 100\");\n      if(type===\"sourceVolumeLink\"&&!['linked','unlinked'].includes(op.state))add(errors,idx,type,\"Link state must be linked or unlinked\");","scene validation");
replaceOnce("  if(type===\"sourceMute\"){","  if(type===\"sourceVolumeLink\"){\n    const linked=op.state!==\"unlinked\";\n    for(const name of sceneNames(op.sources)){\n      const src=findNamedSource(status,name),id=deviceId(src);if(!id)throw new Error(`Scene source not found: ${name}`);\n      const current=sourceLinked(src);if(current===null)throw new Error(`Scene source link state unavailable: ${name}`);\n      if(current===linked)continue;\n      const r=await pipeCommand({Pipewire:{SetSourceVolumeLinked:[id,linked]}});\n      if(!isOk(r)&&!JSON.stringify(r).includes(\"Requested State matches current state\"))throw new Error(`${name}: ${JSON.stringify(r)}`);\n    }\n    return;\n  }\n  if(type===\"sourceMute\"){","scene execution");
replaceOnce("  if(type===\"sourceMute\")return `Source ${op?.mix===\"B\"?\"B\":\"A\"} ${op?.state===\"unmuted\"?\"unmute\":\"mute\"}: ${list(sources)}`;\n  if(type===\"targetMute\")","  if(type===\"sourceMute\")return `Source ${op?.mix===\"B\"?\"B\":\"A\"} ${op?.state===\"unmuted\"?\"unmute\":\"mute\"}: ${list(sources)}`;\n  if(type===\"sourceVolumeLink\")return `Source volume ${op?.state===\"unlinked\"?\"unlink\":\"link\"}: ${list(sources)}`;\n  if(type===\"targetMute\")","scene description");
replaceOnce("      case ACTIONS.sourceMuteB: return toggleSourceMuteForced(i,\"B\");\n      case ACTIONS.targetMixA:","      case ACTIONS.sourceMuteB: return toggleSourceMuteForced(i,\"B\");\n      case ACTIONS.sourceLinkToggle: return toggleSourceVolumeLink(i);\n      case ACTIONS.targetMixA:","key handler");


// v0.16.0 Smart Scenes: declarative conditions, waits, and per-step failure policy.
replaceOnce("function sceneAppLabel(d){return `${d?.name||\"Application\"}${d?.process?` (${d.process})`:\"\"}${d?.deviceType?` [${d.deviceType}]`:\"\"}`}\nfunction validateSceneOperations",`function sceneAppLabel(d){return \`${'${d?.name||"Application"}'}${'${d?.process?` (${d.process})`:""}'}${'${d?.deviceType?` [${d.deviceType}]`:""}'}\`}\nfunction sceneConditionSpec(op){\n  const raw=op?.condition;\n  if(raw===undefined||raw===null)return {type:\"always\",application:null};\n  if(!raw||typeof raw!==\"object\"||Array.isArray(raw))return {type:\"invalid\",application:null};\n  const type=String(raw.type||\"always\");\n  return {type,application:sceneAppDescriptor(raw.application)};\n}\nfunction sceneFailurePolicy(op){return op?.onFailure===\"continue\"?\"continue\":\"stop\"}\nfunction sceneWaitMs(op){const n=Number(op?.milliseconds);return Number.isFinite(n)?Math.round(n):null}\nfunction sceneConditionEvaluation(op,status){\n  const c=sceneConditionSpec(op);\n  if(c.type===\"always\")return {met:true,label:\"Always\"};\n  const label=sceneAppLabel(c.application);\n  const running=!!(c.application&&applications(status).some(a=>sceneAppMatches(a,c.application)));\n  if(c.type===\"applicationRunning\")return {met:running,label:\`Application running: ${'${label}'}\`};\n  if(c.type===\"applicationNotRunning\")return {met:!running,label:\`Application not running: ${'${label}'}\`};\n  return {met:false,label:\"Invalid condition\"};\n}\nfunction sceneSmartDescription(op){\n  const base=sceneOperationDescription(op),c=sceneConditionSpec(op),failure=sceneFailurePolicy(op);\n  let prefix=\"\";\n  if(c.type===\"applicationRunning\")prefix=\`If ${'${sceneAppLabel(c.application)}'} is running: \`;\n  else if(c.type===\"applicationNotRunning\")prefix=\`If ${'${sceneAppLabel(c.application)}'} is not running: \`;\n  return prefix+base+(failure===\"continue\"?\" [continue on failure]\":\"\");\n}\nfunction validateSceneOperations`,"smart scene helpers");
replaceOnce("    const sources=sceneNames(op.sources),targets=sceneNames(op.targets),vol=()=>{const n=Number(op.volume);return String(op.volume??\"\").trim()!==\"\"&&Number.isFinite(n)&&n>=0&&n<=100};\n    if([\"sourceMute\",\"sourceVolume\",\"sourceVolumeLink\"].includes(type)){",`    const sources=sceneNames(op.sources),targets=sceneNames(op.targets),vol=()=>{const n=Number(op.volume);return String(op.volume??\"\").trim()!==\"\"&&Number.isFinite(n)&&n>=0&&n<=100};\n    const condition=sceneConditionSpec(op);\n    if(![\"always\",\"applicationRunning\",\"applicationNotRunning\"].includes(condition.type))add(errors,idx,type,\"Condition must be Always, Application running, or Application not running\");\n    if([\"applicationRunning\",\"applicationNotRunning\"].includes(condition.type)&&!condition.application)add(errors,idx,type,\"Application condition requires an application descriptor\");\n    if(op.onFailure!==undefined&&!['stop','continue'].includes(op.onFailure))add(errors,idx,type,\"Failure policy must be stop or continue\");\n    if(type===\"wait\"){\n      const ms=sceneWaitMs(op);\n      if(ms===null||ms<0||ms>60000)add(errors,idx,type,\"Wait must be between 0 and 60000 milliseconds\");\n    }else if([\"sourceMute\",\"sourceVolume\",\"sourceVolumeLink\"].includes(type)){`,"smart scene validation");
replaceOnce("  const type=String(op.type||\"\");\n  if(type===\"sourceVolumeLink\"){",`  const type=String(op.type||\"\");\n  if(type===\"wait\"){\n    const ms=sceneWaitMs(op);if(ms===null||ms<0||ms>60000)throw new Error(\"Invalid Scene wait\");\n    if(ms>0)await new Promise(resolve=>setTimeout(resolve,ms));\n    return;\n  }\n  if(type===\"sourceVolumeLink\"){`,"wait execution");
replaceOnce("  if(type===\"sourceMute\")return `Source ${op?.mix===\"B\"?\"B\":\"A\"} ${op?.state===\"unmuted\"?\"unmute\":\"mute\"}: ${list(sources)}`;\n  if(type===\"sourceVolumeLink\")",`  if(type===\"wait\")return \`Wait ${'${sceneWaitMs(op)}'} ms\`;\n  if(type===\"sourceMute\")return \`Source ${'${op?.mix==="B"?"B":"A"}'} ${'${op?.state==="unmuted"?"unmute":"mute"}'}: ${'${list(sources)}'}\`;\n  if(type===\"sourceVolumeLink\")`,"wait description");
replaceOnce("    let activeStep=0;", "    let activeStep=0,continuedFailures=0;");
replaceOnce(`      for(let idx=0;idx<ops.length;idx++){\n        activeStep=idx+1;\n        const desc=sceneOperationDescription(ops[idx]);\n        console.log(\`[Scene] STEP ${'${activeStep}'}/${'${ops.length}'} START ${'${desc}'}\`);\n        const stepStarted=Date.now();\n        try{\n          await executeSceneOperation(ops[idx],status);\n          console.log(\`[Scene] STEP ${'${activeStep}'}/${'${ops.length}'} OK ${'${desc}'} (${'${Date.now()-stepStarted}'}ms)\`);\n        }catch(e){\n          console.error(\`[Scene] STEP ${'${activeStep}'}/${'${ops.length}'} FAILED ${'${desc}'}: ${'${e.message}'}\`);\n          throw e;\n        }\n        status=await refreshStatus()||status;\n      }\n      await refreshStatus();\n      console.log(\`[Scene] COMPLETE name=${'${JSON.stringify(sceneName)}'} operations=${'${ops.length}'} duration=${'${Date.now()-started}'}ms\`);\n      showOk(i.context);`, `      for(let idx=0;idx<ops.length;idx++){\n        activeStep=idx+1;\n        const op=ops[idx],desc=sceneSmartDescription(op),condition=sceneConditionEvaluation(op,status);\n        if(!condition.met){\n          console.log(\`[Scene] STEP ${'${activeStep}'}/${'${ops.length}'} SKIP condition not met (${ '${condition.label}' }): ${'${desc}'}\`);\n          status=await refreshStatus()||status;\n          continue;\n        }\n        console.log(\`[Scene] STEP ${'${activeStep}'}/${'${ops.length}'} START ${'${desc}'}\`);\n        const stepStarted=Date.now();\n        try{\n          await executeSceneOperation(op,status);\n          console.log(\`[Scene] STEP ${'${activeStep}'}/${'${ops.length}'} OK ${'${desc}'} (${'${Date.now()-stepStarted}'}ms)\`);\n        }catch(e){\n          const policy=sceneFailurePolicy(op);\n          console.error(\`[Scene] STEP ${'${activeStep}'}/${'${ops.length}'} FAILED ${'${desc}'}: ${'${e.message}'}\`);\n          if(policy===\"continue\"){continuedFailures++;console.warn(\`[Scene] STEP ${'${activeStep}'}/${'${ops.length}'} CONTINUE after failure\`)}\n          else throw e;\n        }\n        status=await refreshStatus()||status;\n      }\n      await refreshStatus();\n      if(continuedFailures){\n        console.warn(\`[Scene] COMPLETE WITH ERRORS name=${'${JSON.stringify(sceneName)}'} operations=${'${ops.length}'} continuedFailures=${'${continuedFailures}'} duration=${'${Date.now()-started}'}ms\`);\n        showAlert(i.context);\n      }else{\n        console.log(\`[Scene] COMPLETE name=${'${JSON.stringify(sceneName)}'} operations=${'${ops.length}'} duration=${'${Date.now()-started}'}ms\`);\n        showOk(i.context);\n      }`,"smart scene execution loop");

const patched=new Module(filename,module);
patched.filename=filename;
patched.paths=module.paths;
patched._compile(source,filename);
